base_url = "/"
title = "mayukh_chr"
build_search_index = false
generate_feed = true
compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/CV", url = "/cv.pdf", weight = 4}
]

socials = [
    {name = "github", url = "https://github.com/mayukh-chr/", icon = "github"},
    {name = "linkedin", url = "https://www.linkedin.com/in/mayukh-chr/",icon = "linkedin"},
    {name = "spotify", url = "https://open.spotify.com/user/zuumtdcue8fsfcq8owwju8i8x?si=8c3c8744363f4d95", icon = "spotify"},
    {name = "twitter", url = "https://twitter.com/mayukh_chr", icon = "twitter"},
]

custom_css = []

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com"    # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is
